service: Quiztopia-api-aws-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: ${env:AWS_REGION}
  iam:
    role: ${env:LAMBDA_ROLE}

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  signup:
    handler: src/functions/public/signup/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: src/functions/public/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
  getAllQuiz:
    handler: src/functions/public/getAllQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz'
          method: GET
  getQuiz:
    handler: src/functions/public/getQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz/{id}'
          method: GET
  createQuiz:
    handler: src/functions/authentication/createQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz'
          method: POST
  addQuestionToQuiz:
    handler: src/functions/authentication/addQuestionToQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz/{id}'
          method: PATCH

resources:
  Resources:
    Quiztopia:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Quiztopia
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
